// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGIds
{
        public const string leaderboard_poo_poo_board = "CgkI-47-7rAZEAIQAQ"; // <GPGSID>
        public const string achievement_addicted_to_feces = "CgkI-47-7rAZEAIQBA"; // <GPGSID>
        public const string achievement_junior_poo = "CgkI-47-7rAZEAIQAg"; // <GPGSID>
        public const string achievement_holy_crap = "CgkI-47-7rAZEAIQBg"; // <GPGSID>
        public const string achievement_ranked_manure = "CgkI-47-7rAZEAIQAw"; // <GPGSID>
        public const string achievement_the_poominator = "CgkI-47-7rAZEAIQBQ"; // <GPGSID>

}

